package com.locket.common.services;

import java.util.HashMap;
public class DmaMapServices {
	
	private static HashMap<String, String> dmaMap;

	static{
		dmaMap = new HashMap<String, String>();
		dmaMap.put("000", "New York"); 
		dmaMap.put("001", "Los Angeles"); 
		dmaMap.put("002", "Chicago"); 
		dmaMap.put("003", "Philadelphia"); 
		dmaMap.put("004", "Dallas-Ft Worth"); 
		dmaMap.put("005", "San Francisco-Oak-San Jose"); 
		dmaMap.put("006", "Boston (Manchester)"); 
		dmaMap.put("007", "Washington DC (Hagrstwn)"); 
		dmaMap.put("008", "Atlanta"); 
		dmaMap.put("009", "Houston"); 
		dmaMap.put("010", "Detroit"); 
		dmaMap.put("011", "Seattle-Tacoma"); 
		dmaMap.put("012", "Phoenix (Prescott)"); 
		dmaMap.put("013", "Tampa-St Pete (Sarasota)"); 
		dmaMap.put("014", "Minneapolis-St Paul"); 
		dmaMap.put("015", "Miami-Ft Lauderdale"); 
		dmaMap.put("016", "Denver"); 
		dmaMap.put("017", "Cleveland Akron-(Canton)"); 
		dmaMap.put("018", "Orlando-Daytona Bch-Melbrn"); 
		dmaMap.put("019", "Sacramnto-Stkton-Modesto"); 
		dmaMap.put("020", "St Louis"); 
		dmaMap.put("021", "Portland OR"); 
		dmaMap.put("022", "Pittsburgh"); 
		dmaMap.put("023", "Raleigh-Durham (Fayetvlle)"); 
		dmaMap.put("024", "Charlotte"); 
		dmaMap.put("025", "Indianapolis"); 
		dmaMap.put("026", "Baltimore"); 
		dmaMap.put("027", "San Diego"); 
		dmaMap.put("028", "Nashville"); 
		dmaMap.put("029", "Hartford & New Haven"); 
		dmaMap.put("030", "Kansas City"); 
		dmaMap.put("031", "Columbus OH"); 
		dmaMap.put("032", "Salt Lake City"); 
		dmaMap.put("033", "Milwaukee"); 
		dmaMap.put("034", "Cincinnati"); 
		dmaMap.put("035", "San Antonio"); 
		dmaMap.put("036", "Greenvll-Spart-Ashevll-And"); 
		dmaMap.put("037", "West Palm Beach-Ft Pierce"); 
		dmaMap.put("038", "Grand Rapids-Kalmzoo-BCrk"); 
		dmaMap.put("039", "Las Vegas"); 
		dmaMap.put("040", "Oklahoma City"); 
		dmaMap.put("041", "Birmingham (Ann and Tusc)"); 
		dmaMap.put("042", "Harrisburg-Lncstr-Leb-York"); 
		dmaMap.put("043", "Norfolk-Portsmth-Newpt Nws"); 
		dmaMap.put("044", "Austin"); 
		dmaMap.put("045", "Greensboro-HPoint-WSalem"); 
		dmaMap.put("046", "Albuquerque-Santa Fe"); 
		dmaMap.put("047", "Louisville"); 
		dmaMap.put("048", "Memphis"); 
		dmaMap.put("049", "Jacksonville"); 
		dmaMap.put("050", "New Orleans"); 
		dmaMap.put("051", "Buffalo"); 
		dmaMap.put("052", "Providence-New Bedford"); 
		dmaMap.put("053", "Wilkes Barre-Scranton-Hztn"); 
		dmaMap.put("054", "Fresno-Visalia"); 
		dmaMap.put("055", "Little Rock-Pine Bluff"); 
		dmaMap.put("056", "Richmond-Petersburg"); 
		dmaMap.put("057", "Albany Schenectady Troy"); 
		dmaMap.put("058", "Tulsa"); 
		dmaMap.put("059", "Mobile-Pensacola (Ft Walt)"); 
		dmaMap.put("060", "Knoxville"); 
		dmaMap.put("061", "Ft Myers-Naples"); 
		dmaMap.put("062", "Dayton"); 
		dmaMap.put("063", "Lexington"); 
		dmaMap.put("064", "Charleston-Huntington"); 
		dmaMap.put("065", "Wichita-Hutchinson Plus"); 
		dmaMap.put("066", "Flint-Saginaw-Bay City"); 
		dmaMap.put("067", "Roanoke-Lynchburg"); 
		dmaMap.put("068", "Green Bay-Appleton"); 
		dmaMap.put("069", "Tucson (Sierra Vista)"); 
		dmaMap.put("070", "Honolulu"); 
		dmaMap.put("071", "Des Moines-Ames"); 
		dmaMap.put("072", "Spokane"); 
		dmaMap.put("073", "Springfield MO"); 
		dmaMap.put("074", "Omaha"); 
		dmaMap.put("075", "Toledo"); 
		dmaMap.put("076", "Columbia SC"); 
		dmaMap.put("077", "Rochester NY"); 
		dmaMap.put("078", "Huntsville-Decatur (Flor)"); 
		dmaMap.put("079", "Portland-Auburn"); 
		dmaMap.put("080", "Paducah-Cape Girard-Harsbg"); 
		dmaMap.put("081", "Shreveport"); 
		dmaMap.put("082", "Champaign&Sprngfld-Decatur"); 
		dmaMap.put("083", "Syracuse"); 
		dmaMap.put("084", "Madison"); 
		dmaMap.put("085", "Harlingen-Wslco-Brnsvl-McA"); 
		dmaMap.put("086", "Chattanooga"); 
		dmaMap.put("087", "Waco-Temple-Bryan"); 
		dmaMap.put("088", "Colorado Springs-Pueblo"); 
		dmaMap.put("089", "Cedar Rapids-Wtrlo-IWC&Dub"); 
		dmaMap.put("090", "El Paso (Las Cruces)"); 
		dmaMap.put("091", "Savannah"); 
		dmaMap.put("092", "Jackson MS"); 
		dmaMap.put("093", "Baton Rouge"); 
		dmaMap.put("094", "South Bend-Elkhart"); 
		dmaMap.put("095", "Tri-Cities TN-VA"); 
		dmaMap.put("096", "Burlington-Plattsburgh"); 
		dmaMap.put("097", "Charleston SC"); 
		dmaMap.put("098", "Davenport-RIsland-Moline"); 
		dmaMap.put("099", "Greenville-NBern-Washngtn"); 
		dmaMap.put("100", "Ft Smith-Fay-Sprngdl-Rgrs"); 
		dmaMap.put("101", "Johnstown-Altoona-St Colge"); 
		dmaMap.put("102", "Myrtle Beach-Florence"); 
		dmaMap.put("103", "Evansville"); 
		dmaMap.put("104", "Lincoln & Hastings-Krny"); 
		dmaMap.put("105", "Tallahassee-Thomasville"); 
		dmaMap.put("106", "Tyler-Longview(Lfkn&Ncgd)"); 
		dmaMap.put("107", "Reno"); 
		dmaMap.put("108", "Ft Wayne"); 
		dmaMap.put("109", "Youngstown"); 
		dmaMap.put("110", "Boise"); 
		dmaMap.put("111", "Sioux Falls(Mitchell)"); 
		dmaMap.put("112", "Augusta-Aiken"); 
		dmaMap.put("113", "Springfield-Holyoke"); 
		dmaMap.put("114", "Lansing"); 
		dmaMap.put("115", "Peoria-Bloomington"); 
		dmaMap.put("116", "Fargo-Valley City"); 
		dmaMap.put("117", "Montgomery-Selma"); 
		dmaMap.put("118", "Traverse City-Cadillac"); 
		dmaMap.put("119", "Macon"); 
		dmaMap.put("120", "Eugene"); 
		dmaMap.put("121", "SantaBarbra-SanMar-SanLuOb"); 
		dmaMap.put("122", "Yakima-Pasco-Rchlnd-Knnwck"); 
		dmaMap.put("123", "Lafayette LA"); 
		dmaMap.put("124", "Monterey-Salinas"); 
		dmaMap.put("125", "Bakersfield"); 
		dmaMap.put("126", "Columbus GA (Opelika AL)"); 
		dmaMap.put("127", "La Crosse-Eau Claire"); 
		dmaMap.put("128", "Corpus Christi"); 
		dmaMap.put("129", "Amarillo"); 
		dmaMap.put("130", "Chico-Redding"); 
		dmaMap.put("131", "Wilmington"); 
		dmaMap.put("132", "Columbus-Tupelo-W Pnt-Hstn"); 
		dmaMap.put("133", "Wausau-Rhinelander"); 
		dmaMap.put("134", "Rockford"); 
		dmaMap.put("135", "Topeka"); 
		dmaMap.put("136", "Monroe-El Dorado"); 
		dmaMap.put("137", "Columbia-Jefferson City"); 
		dmaMap.put("138", "Duluth-Superior"); 
		dmaMap.put("139", "Medford-Klamath Falls"); 
		dmaMap.put("140", "Beaumont-Port Arthur"); 
		dmaMap.put("141", "Lubbock"); 
		dmaMap.put("142", "Wichita Falls & Lawton"); 
		dmaMap.put("143", "Salisbury"); 
		dmaMap.put("144", "Anchorage"); 
		dmaMap.put("145", "Erie"); 
		dmaMap.put("146", "Sioux City"); 
		dmaMap.put("147", "Palm Springs"); 
		dmaMap.put("148", "Joplin-Pittsburg"); 
		dmaMap.put("149", "Albany GA"); 
		dmaMap.put("150", "Minot-Bsmrck-Dcknsn(Wlstn)"); 
		dmaMap.put("151", "Odessa-Midland"); 
		dmaMap.put("152", "Rochestr-Mason City-Austin"); 
		dmaMap.put("153", "Terre Haute"); 
		dmaMap.put("154", "Bangor"); 
		dmaMap.put("155", "Bluefield-Beckley-Oak Hill"); 
		dmaMap.put("156", "Binghamton"); 
		dmaMap.put("157", "Wheeling-Steubenville"); 
		dmaMap.put("158", "Panama City"); 
		dmaMap.put("159", "Biloxi-Gulfport"); 
		dmaMap.put("160", "Sherman-Ada"); 
		dmaMap.put("161", "Idaho Fals-Pocatllo(Jcksn)"); 
		dmaMap.put("162", "Gainesville"); 
		dmaMap.put("163", "Abilene-Sweetwater"); 
		dmaMap.put("164", "Yuma-El Centro"); 
		dmaMap.put("165", "Missoula"); 
		dmaMap.put("166", "Hattiesburg-Laurel"); 
		dmaMap.put("167", "Billings"); 
		dmaMap.put("168", "Dothan"); 
		dmaMap.put("169", "Clarksburg-Weston"); 
		dmaMap.put("170", "Quincy-Hannibal-Keokuk"); 
		dmaMap.put("171", "Utica"); 
		dmaMap.put("172", "Rapid City"); 
		dmaMap.put("173", "Elmira (Corning)"); 
		dmaMap.put("174", "Lake Charles"); 
		dmaMap.put("175", "Jackson TN"); 
		dmaMap.put("176", "Watertown"); 
		dmaMap.put("177", "Harrisonburg"); 
		dmaMap.put("178", "Alexandria LA"); 
		dmaMap.put("179", "Marquette"); 
		dmaMap.put("180", "Jonesboro"); 
		dmaMap.put("181", "Bowling Green"); 
		dmaMap.put("182", "Charlottesville"); 
		dmaMap.put("183", "Laredo"); 
		dmaMap.put("184", "Grand Junction-Montrose"); 
		dmaMap.put("185", "Meridian"); 
		dmaMap.put("186", "Butte-Bozeman"); 
		dmaMap.put("187", "Greenwood-Greenville"); 
		dmaMap.put("188", "Lafayette IN"); 
		dmaMap.put("189", "Great Falls"); 
		dmaMap.put("190", "Twin Falls"); 
		dmaMap.put("191", "Bend OR"); 
		dmaMap.put("192", "Parkersburg"); 
		dmaMap.put("193", "Eureka"); 
		dmaMap.put("194", "Cheyenne-Scottsbluff"); 
		dmaMap.put("195", "San Angelo"); 
		dmaMap.put("196", "Casper-Riverton"); 
		dmaMap.put("197", "Mankato"); 
		dmaMap.put("198", "Lima"); 
		dmaMap.put("199", "Ottumwa-Kirksville"); 
		dmaMap.put("200", "St Joseph"); 
		dmaMap.put("201", "Fairbanks"); 
		dmaMap.put("202", "Zanesville"); 
		dmaMap.put("203", "Victoria"); 
		dmaMap.put("204", "Presque Isle"); 
		dmaMap.put("205", "Helena"); 
		dmaMap.put("206", "Juneau"); 
		dmaMap.put("207", "Alpena"); 
		dmaMap.put("208", "North Platte"); 
		dmaMap.put("209", "Glendive"); 
	}

	public static String getTagValue(String key){
		return dmaMap.get(key);
	}





}